<a href="https://colab.research.google.com/github/rozaneekantadas/Machine-Learning-Practice/blob/main/Linear_Regression_Using_Multiple_Val.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Regression Using Multiple variable

In [ ]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp36-none-any.whl size=5588 sha256=a042751045b73041d24d6214784b515a9e7d0df33c3b970fd809b590ab495e12
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [ ]:
path = "/content/homeprices.csv"
df = pd.read_csv(path)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
median = df.bedrooms.median()

In [ ]:
df.bedrooms = df.bedrooms.fillna(median)
df 

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
model = linear_model.LinearRegression()

In [ ]:
model.fit(df.drop('price', axis = 'columns') , df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [ ]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
model.intercept_

221323.00186540396

### Excersice

In [ ]:
path = '/content/hiring.csv'
d = pd.read_csv(path)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
d['experience'] = d.experience.fillna('zero')
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
#d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [ ]:
median = d['test_score(out of 10)'].median()
median

8.0

In [ ]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
model_salary = linear_model.LinearRegression()

In [ ]:
model_salary.fit(d.drop('salary($)',axis = "columns") ,d['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model_salary.predict([[2,9,6]])

array([53205.96797671])